import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
// import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import { PageContainer } from "@/components/page-container";
import { I18nProvider } from "@/lib/i18n/provider";
import { Setup } from "@/components/setup/setup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await auth();

  return (
    // <SessionProvider session={session}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider>
          <Setup>
            <PageContainer back={false}>
              <Toaster />

              {children}
            </PageContainer>
          </Setup>
        </I18nProvider>
      </body>
    </html>
    // </SessionProvider>
  );
}
